# Generated by Django 4.2.6 on 2024-02-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('complete', 'completed'), ('pending', 'pending')], max_length=50),
        ),
    ]
